# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

# name: Spring Boot CI

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     env:
#       gmail_password: ${{secrets.gmail_password}}
#       mongo_uri: ${{secrets.mongo_uri}}
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up JDK 17
#       uses: actions/setup-java@v2
#       with:
#         java-version: '17'
#         distribution: 'adopt'
#     - name: Build with Maven
#       run: mvn clean install
